"""Category-specific false negative test."""
import sys, time
sys.path.insert(0, ".")
from unified_pipeline import UnifiedPipeline

CATEGORIES = {
    "SVA": [
        ('She go to school every day.', 'goes'),
        ('The dogs runs very fast.', 'run'),
        ("He don't know the answer.", "doesn't"),
        ("They doesn't like ice cream.", "don't"),
        ('The list of items are on the table.', 'is'),
        ('Everyone have their own opinion.', 'has'),
        ('Nobody know the truth.', 'knows'),
        ('The news are bad today.', 'is'),
        ('Five dollars are too much.', 'is'),
        ('Each of the students have a book.', 'has'),
        ('Neither of them were ready.', 'was'),
        ('He have been working hard.', 'has'),
        ('She were at the store yesterday.', 'was'),
        ('The teacher explain the lesson clearly.', 'explains'),
        ('My brother play basketball every weekend.', 'plays'),
        ('There is many reasons to celebrate.', 'are'),
        ('The information were misleading.', 'was'),
        ('Somebody have left their umbrella.', 'has'),
        ('Every one of the cakes were delicious.', 'was'),
        ('The police is investigating the crime.', 'are'),
        ('The furniture are expensive.', 'is'),
        ('The number of applicants are increasing.', 'is'),
        ('Mathematics are my favorite subject.', 'is'),
        ('The committee have reached a decision.', 'has'),
        ("She don't understand the problem.", "doesn't"),
        ('The audience are clapping their hands.', 'is'),
        ('Everyone were happy.', 'was'),
        ('Nobody were interested.', 'was'),
        ('Each of the boys have finished.', 'has'),
        ('Half of the cake are missing.', 'is'),
        ('Most of the water are gone.', 'is'),
        ('All of the food were delicious.', 'was'),
        ('Some of the milk have spilled.', 'has'),
        ('Either the manager or the employees was wrong.', 'were'),
        ('Neither the teacher nor the students was prepared.', 'were'),
        ("He don't has any money.", "doesn't have"),
        ('Bread and butter are my favorite breakfast.', 'is'),
        ('Tom and Jerry is a cartoon.', 'are'),
        ('The family are going on vacation.', 'is'),
        ('None of the above are correct.', 'is'),
        ('The number of people is increasing every day.', 'The number is already singular'),
        ('Me and him went to the store.', 'He and I'),
        ('Her and me are going to the park.', 'She and I'),
        ('Him and her went to the movies.', 'He and she'),
        ('The team are winning the game.', 'is'),
        ('The children was very excited.', 'were'),
        ('Everybody have finished their homework.', 'has'),
        ('A lot of people was waiting outside.', 'were'),
        ('The pants is too long.', 'are'),
        ("She don't play well.", "doesn't"),
        ('He do not know the answer.', 'does not'),
    ],
    "DO_SUPPORT": [
        ('She like cats.', 'likes'),
        ('He go to school.', 'goes'),
        ('They comes every day.', 'come'),
        ('Does she likes coffee?', 'like'),
        ('Do he play basketball?', 'Does'),
        ("She don't like Mondays.", "doesn't"),
        ("He don't have a car.", "doesn't"),
        ("They don't knows the answer.", 'know'),
        ('Does he goes to work?', 'go'),
        ('Do she have a pen?', 'Does'),
        ("He don't wants to go.", "doesn't want"),
        ("She don't think so.", "doesn't"),
        ("They don't understands.", 'understand'),
        ('He do goes to school.', 'goes'),
        ('She do likes coffee.', 'likes'),
        ('Do they goes home?', 'go'),
        ("He don't needs help.", "doesn't need"),
        ("She don't has time.", "doesn't have"),
        ("They don't plays well.", 'play'),
        ('He do is a good student.', 'is'),
        ('She do can swim.', 'can'),
        ('They do goes to school.', 'go'),
        ("He don't wants to leave.", "doesn't want"),
        ("She don't believes him.", "doesn't believe"),
        ("We don't knows the answer.", 'know'),
        ('He do play basketball.', 'plays'),
        ('She do goes home.', 'goes'),
        ('They do likes coffee.', 'like'),
        ("He don't needs no help.", "doesn't need"),
        ("She don't wants any trouble.", "doesn't want"),
        ('We do goes to church.', 'go'),
        ('He do has a car.', 'has'),
        ('She do have a pen.', 'has'),
        ('They do can swim.', 'can'),
        ('He do will come.', 'will'),
        ('She do should go.', 'should'),
        ('They do must leave.', 'must'),
        ('He do may come.', 'may'),
        ('She do would like that.', 'would'),
        ('They do could help.', 'could'),
        ('He do might be late.', 'might'),
        ('She do can sing.', 'can'),
        ('They do shall we?', 'shall'),
        ('He do can not swim.', 'cannot'),
        ('She do will not come.', 'will not'),
        ('They do should have gone.', 'should have'),
        ('He do must go.', 'must'),
        ('She do may be right.', 'may'),
        ('They do would have helped.', 'would have'),
    ],
    "TENSE_CONSISTENCY": [
        ('Yesterday I go to the store.', 'went'),
        ('She walk to school yesterday.', 'walked'),
        ('He is eat his lunch.', 'eating'),
        ('They was play all day.', 'played'),
        ('I was go to the movies.', 'going'),
        ('She have finished the project.', 'has'),
        ('He walk home after school.', 'walked'),
        ('They arrives late every day.', 'arrive'),
        ('Yesterday she cook dinner.', 'cooked'),
        ('Last week I visit my parents.', 'visited'),
        ('He is run every morning.', 'runs'),
        ('She was study all night.', 'studying'),
        ('They were go to the park.', 'going'),
        ('I am went to the store.', 'going'),
        ('He am finished the project.', 'has'),
        ('We was have a good time.', 'having'),
        ('She is called me yesterday.', 'called'),
        ('He is eat lunch at noon.', 'eats'),
        ('They is goes to school.', 'go'),
        ('We is was at home.', 'were'),
        ('I was am a student.', 'was'),
        ('She were is a doctor.', 'was'),
        ('He were goes home.', 'went'),
        ('They was go to school.', 'went'),
        ('We were is coming.', 'were'),
        ('I go to the store yesterday.', 'went'),
        ('She goes to school yesterday.', 'went'),
        ('He come home late yesterday.', 'came'),
        ('They run in the park yesterday.', 'ran'),
        ('We eat lunch at noon yesterday.', 'ate'),
        ('I see a movie last night.', 'saw'),
        ('She take a taxi this morning.', 'took'),
        ('He give her a gift yesterday.', 'gave'),
        ('They buy a new car last week.', 'bought'),
        ('We meet our friends yesterday.', 'met'),
        ('I find my keys yesterday.', 'found'),
        ('She bring her friend yesterday.', 'brought'),
        ('He tell me the story yesterday.', 'told'),
        ('They show us the picture yesterday.', 'showed'),
        ('We choose the red one yesterday.', 'chose'),
        ('I write a letter yesterday.', 'wrote'),
        ('She read a book last night.', 'read'),
        ('He drive to work yesterday.', 'drove'),
        ('They sing a song yesterday.', 'sang'),
        ('We think about it yesterday.', 'thought'),
        ('I feel tired yesterday.', 'felt'),
        ('She leave early yesterday.', 'left'),
        ('He know the answer yesterday.', 'knew'),
        ('They mean what they say yesterday.', 'meant'),
    ],
    "DIDNT_PAST_FORM": [
        ("I didn't went to school.", 'go'),
        ("She didn't came back.", 'come'),
        ("He didn't saw the movie.", 'see'),
        ("They didn't ate dinner.", 'eat'),
        ("We didn't knew the answer.", 'know'),
        ("I didn't had enough money.", 'have'),
        ("He didn't took the test.", 'take'),
        ("She didn't bought the dress.", 'buy'),
        ("They didn't wrote the report.", 'write'),
        ("I didn't spoke to her.", 'speak'),
        ("We didn't ran fast enough.", 'run'),
        ("He didn't gave me the money.", 'give'),
        ("I didn't felt well.", 'feel'),
        ("She didn't thought about it.", 'think'),
        ("They didn't left early.", 'leave'),
        ("He didn't kept his promise.", 'keep'),
        ("I didn't slept well last night.", 'sleep'),
        ("She didn't read the book.", 'read'),
        ("We didn't drove to the airport.", 'drive'),
        ("They didn't chose the right option.", 'choose'),
        ("I didn't wore my coat.", 'wear'),
        ("He didn't broke the window.", 'break'),
        ("She didn't caught the ball.", 'catch'),
        ("They didn't taught the students.", 'teach'),
        ("I didn't lost my keys.", 'lose'),
        ("We didn't met them before.", 'meet'),
        ("He didn't spent too much.", 'spend'),
        ("She didn't won the game.", 'win'),
        ("I didn't told you.", 'tell'),
        ("They didn't built the house.", 'build'),
        ("He didn't sat down.", 'sit'),
        ("I didn't stood up.", 'stand'),
        ("She didn't drew the picture.", 'draw'),
        ("We didn't grew tomatoes.", 'grow'),
        ("They didn't sang the song.", 'sing'),
        ("I didn't fell down.", 'fall'),
        ("He didn't shook hands.", 'shake'),
        ("She didn't bit the apple.", 'bite'),
        ("I didn't hid the money.", 'hide'),
        ("We didn't threw the ball.", 'throw'),
        ("He didn't blew the whistle.", 'blow'),
        ("She didn't froze the food.", 'freeze'),
        ("They didn't chose carefully.", 'choose'),
        ("I didn't slept enough.", 'sleep'),
        ("He didn't stole the car.", 'steal'),
        ("She didn't tore the paper.", 'tear'),
        ("We didn't woke up early.", 'wake'),
        ("They didn't tore the fabric.", 'tear'),
        ("I didn't woke up on time.", 'wake'),
        ("He didn't drove carefully.", 'drive'),
    ],
    "ARTICLE_MISSING": [
        ('I went to store yesterday.', 'the store'),
        ('She is student at the university.', 'a student'),
        ('He is best player on the team.', 'the best'),
        ('They live in small town.', 'a small town'),
        ('We need to discuss matter.', 'the matter'),
        ('She works at hospital.', 'a hospital'),
        ('He bought new car.', 'a new car'),
        ('We had great time.', 'a great time'),
        ('She is teacher.', 'a teacher'),
        ('He went to dentist.', 'the dentist'),
        ('They visited museum.', 'the museum'),
        ('We watched movie.', 'a movie'),
        ('She read book.', 'a book'),
        ('He plays piano.', 'the piano'),
        ('They went to concert.', 'a concert'),
        ('We live in apartment.', 'an apartment'),
        ('She needs umbrella.', 'an umbrella'),
        ('He is president of company.', 'the president'),
        ('They bought house.', 'a house'),
        ('We had argument.', 'an argument'),
        ('She has headache.', 'a headache'),
        ('He made mistake.', 'a mistake'),
        ('They won prize.', 'a prize'),
        ('We need to discuss it with manager.', 'the manager'),
        ('She is at library.', 'the library'),
        ('He works at bank.', 'a bank'),
        ('They are having baby.', 'a baby'),
        ('We live near park.', 'a park'),
        ('She needs glass of water.', 'a glass'),
        ('He drove truck.', 'a truck'),
        ('They found solution.', 'a solution'),
        ('We watched movie last night.', 'a movie'),
        ('She wore dress.', 'a dress'),
        ('He bought suit.', 'a suit'),
        ('They took vacation.', 'a vacation'),
        ('She started new business.', 'a new business'),
        ('He is at door.', 'the door'),
        ('We need to discuss it.', ''),
        ('She is in kitchen.', 'the kitchen'),
        ('He went to office.', 'the office'),
        ('They are in garden.', 'the garden'),
        ('We had dinner.', 'dinner'),
        ('She is at work.', 'work'),
        ('He went to school.', 'school'),
        ('They are at home.', 'home'),
        ('We went to church.', 'church'),
        ('She is in bed.', 'bed'),
        ('He went to prison.', 'prison'),
        ('They are in class.', 'class'),
    ],
    "MODAL_WRONG_FORM": [
        ('She can sings beautifully.', 'sing'),
        ('He will goes to the store.', 'go'),
        ('They should studies harder.', 'study'),
        ('We must to leave now.', 'leave'),
        ('She may comes tomorrow.', 'come'),
        ('He could helps you.', 'help'),
        ('They would enjoys it.', 'enjoy'),
        ('We should to wait.', 'wait'),
        ('I can to swim.', 'swim'),
        ('She will has finished.', 'have'),
        ('He must to go.', 'go'),
        ('They might takes a taxi.', 'take'),
        ('We could to try harder.', 'try'),
        ('She should to study.', 'study'),
        ('He will goes home.', 'go'),
        ('They can sings well.', 'sing'),
        ('We may to go.', 'go'),
        ('I must to finish.', 'finish'),
        ('She would enjoys it.', 'enjoy'),
        ('He could to help.', 'help'),
        ('They should to go.', 'go'),
        ('We must tries harder.', 'try'),
        ('I may to come.', 'come'),
        ('She will goes there.', 'go'),
        ('He can to speak.', 'speak'),
        ('They must to leave.', 'leave'),
        ('We could goes there.', 'go'),
        ('I should to check.', 'check'),
        ('She may goes now.', 'go'),
        ('He will helps me.', 'help'),
        ('They could sings.', 'sing'),
        ('We should to help.', 'help'),
        ('I would to go.', 'go'),
        ('She must goes.', 'go'),
        ('He can helps.', 'help'),
        ('They will goes.', 'go'),
        ('We may to try.', 'try'),
        ('I could to see.', 'see'),
        ('She should goes.', 'go'),
        ('He must helps.', 'help'),
        ('They can goes.', 'go'),
        ('We would to try.', 'try'),
        ('I might to come.', 'come'),
        ('She will helps.', 'help'),
        ('He could goes.', 'go'),
        ('They should helps.', 'help'),
        ('We must goes.', 'go'),
        ('I may helps.', 'help'),
        ('She can goes.', 'go'),
        ('He will helps.', 'help'),
    ],
    "WRONG_PAST_PARTICIPLE": [
        ('She has went to the store.', 'gone'),
        ('He has ate all the food.', 'eaten'),
        ('They has wrote the report.', 'written'),
        ('We has drove to the airport.', 'driven'),
        ('I has saw that movie.', 'seen'),
        ('She has took the test.', 'taken'),
        ('He has gave her a gift.', 'given'),
        ('They has spoke to the manager.', 'spoken'),
        ('I has broke the vase.', 'broken'),
        ('She has chose the blue one.', 'chosen'),
        ('He has flew to London.', 'flown'),
        ('We has drank all the water.', 'drunk'),
        ('I has begun to understand.', 'begun'),
        ('They has run out of time.', 'run'),
        ('She has woke up early.', 'woken'),
        ('He has froze the food.', 'frozen'),
        ('We has grew the vegetables.', 'grown'),
        ('I has threw the ball.', 'thrown'),
        ('She has known him for years.', 'known'),
        ('They has left already.', 'left'),
        ('He has fell asleep.', 'fallen'),
        ('We has hidden the treasure.', 'hidden'),
        ('I has forgot my keys.', 'forgotten'),
        ('She has bit her lip.', 'bitten'),
        ('He has woke the children.', 'woken'),
        ('They has tore the paper.', 'torn'),
        ('We has blew out the candles.', 'blown'),
        ('I has shook his hand.', 'shaken'),
        ('She has stole the money.', 'stolen'),
        ('He has woken up.', 'woken'),
        ('They has began the project.', 'begun'),
        ('We has sunk the ship.', 'sunk'),
        ('I has drunk too much.', 'drunk'),
        ('She has swam across the lake.', 'swum'),
        ('He has rang the bell.', 'rung'),
        ('They has sprang into action.', 'sprung'),
        ('We has ate lunch.', 'eaten'),
        ('I has went home.', 'gone'),
        ('She has spoke to him.', 'spoken'),
        ('He has ran a marathon.', 'run'),
        ('They has gave the presentation.', 'given'),
        ('We has wrote the letter.', 'written'),
        ('I has drove there.', 'driven'),
        ('She has took the medicine.', 'taken'),
        ('He has swam in the ocean.', 'swum'),
        ('They has blown the whistle.', 'blown'),
        ('We has saw the results.', 'seen'),
        ('I has begun to see.', 'begun'),
        ('She has grew taller.', 'grown'),
        ('He has froze the pipes.', 'frozen'),
    ],
    "MISSING_APOSTROPHE": [
        ("The dog wagged it's tail.", 'its'),
        ("She lost her dog's bone.", "dog's"),
        ("The teacher's desk is clean.", "teachers'"),
        ('My parents house is big.', "parents'"),
        ('The childrens toys are here.', "children's"),
        ('The dogs bone is buried.', "dog's"),
        ("She borrowed her friend's car.", "friends'"),
        ('The students books are on the table.', "students'"),
        ("He went to his friend's house.", "friends'"),
        ("The company's policy is clear.", ''),
        ("The women's rights are important.", ''),
        ("My brother's car is red.", ''),
        ('The cats food is on the floor.', "cat's"),
        ('The babies parents are worried.', "babies'"),
        ("She wore her mother's dress.", ''),
        ('The teams coach gave a speech.', "team's"),
        ("He is at his grandmother's house.", ''),
        ('The managers meeting is at noon.', "managers'"),
        ('The doctors office is closed.', "doctor's"),
        ('The nurses station is nearby.', "nurses'"),
        ('She left her childs toys outside.', "child's"),
        ('The mens room is upstairs.', "men's"),
        ('The womens restroom is downstairs.', "women's"),
        ('My aunts house is nearby.', "aunt's"),
        ('The horses stable is clean.', "horse's"),
        ('The birds nest is in the tree.', "bird's"),
        ('He fixed the cars engine.', "car's"),
        ('The planets orbit is elliptical.', "planet's"),
        ('She loves her husbands cooking.', "husband's"),
        ('The childs mother was worried.', "child's"),
    ],
    "COMMA_SPLICE": [
        ('I love to read, she prefers movies.', 'I love to read; she prefers movies.'),
        ('The cat is black, the dog is white.', 'The cat is black, and the dog is white.'),
        ('He went to the store, he bought some milk.', 'He went to the store, and he bought some milk.'),
        ('She studied hard, she passed the exam.', 'She studied hard, so she passed the exam.'),
        ('It was raining, we stayed inside.', 'It was raining, so we stayed inside.'),
        ('The movie was long, it was good.', 'The movie was long, but it was good.'),
        ('I wanted to go, I was too tired.', 'I wanted to go, but I was too tired.'),
        ('She likes coffee, he prefers tea.', 'She likes coffee, and he prefers tea.'),
        ('We could leave early, we chose to stay.', 'We could leave early, but we chose to stay.'),
        ('The results were good, the team was happy.', 'The results were good, so the team was happy.'),
        ('He finished the work, he went home.', 'He finished the work, and he went home.'),
        ('She was tired, she kept working.', 'She was tired, but she kept working.'),
        ('It was cold outside, we wore jackets.', 'It was cold outside, so we wore jackets.'),
        ('The food was ready, we sat down to eat.', 'The food was ready, and we sat down to eat.'),
        ('He called me, I did not answer.', 'He called me, but I did not answer.'),
        ('She arrived late, the meeting had started.', 'She arrived late, and the meeting had started.'),
        ('They practiced every day, they improved quickly.', 'They practiced every day, so they improved quickly.'),
        ('The project was difficult, we finished it.', 'The project was difficult, but we finished it.'),
        ('He is smart, he is lazy.', 'He is smart, but he is lazy.'),
        ('She sang beautifully, the audience clapped.', 'She sang beautifully, and the audience clapped.'),
    ],
    "PREPOSITION_COLLOCATION": [
        ('She is good in math.', 'at'),
        ('He is afraid from spiders.', 'of'),
        ('They are waiting to the bus.', 'for'),
        ('I am interested for learning.', 'in'),
        ('She is worried to the exam.', 'about'),
        ('He is responsible to the project.', 'for'),
        ('They are arguing to politics.', 'about'),
        ('We are planning in the future.', 'for'),
        ('I am proud in my children.', 'of'),
        ('She is jealous from her sister.', 'of'),
        ('He is capable for doing the job.', 'of'),
        ('They are fond in outdoor activities.', 'of'),
        ('We are tired in waiting.', 'of'),
        ('I am familiar to this software.', 'with'),
        ('She is dependent from her parents.', 'on'),
        ('He is addicted in video games.', 'to'),
        ('They are committed for the cause.', 'to'),
        ('We are opposed in the plan.', 'to'),
        ('I am used in working long hours.', 'to'),
        ('She is accustomed for the cold.', 'to'),
        ('He is sensitive from criticism.', 'to'),
        ('I disagree in your opinion.', 'with'),
        ('She specializes on pediatric medicine.', 'in'),
        ('He apologized to being late.', 'for'),
        ('They are grateful to your help.', 'for'),
        ('We are concerned to the environment.', 'about'),
        ('She is confident in her abilities.', 'about'),
        ('He is looking for to meeting you.', 'forward'),
        ('I am looking in the matter.', 'into'),
        ('She is checking in the children.', 'on'),
        ('He is running at problems.', 'into'),
        ('They are setting in the equipment.', 'up'),
        ('We are carrying in the plan.', 'out'),
        ('I am falling in my studies.', 'behind'),
        ('She is running in of patience.', 'out'),
        ('He is breaking in the problem.', 'down'),
        ('They are working in at the gym.', 'out'),
        ('We are picking in new skills.', 'up'),
        ('I am putting in weight.', 'on'),
        ('She is turning in the offer.', 'down'),
        ('He is giving in smoking.', 'up'),
        ('They are breaking in up.', ''),
        ('We are splitting in the work.', 'up'),
        ('I am checking in at.', 'in'),
        ('She is following in on the case.', 'up'),
        ('He is catching in on work.', 'up'),
        ('They are tidying in the house.', 'up'),
        ('We are clearing in the misunderstanding.', 'up'),
        ('She is making in up for lost time.', ''),
    ],
    "DOUBLE_COMPARATIVE": [
        ('She is more taller than her sister.', 'taller'),
        ('He is most intelligent in the class.', 'the most'),
        ('This is the more better option.', 'better'),
        ('She is most tallest in the school.', 'the tallest'),
        ('He is more stronger than he looks.', 'stronger'),
        ('This is the most easiest exam.', 'easiest'),
        ('She is more prettier than her friend.', 'prettier'),
        ('He is more heavier than his brother.', 'heavier'),
        ('This is the most highest building.', 'highest'),
        ('She is more smarter than she thinks.', 'smarter'),
        ('He is less smarter than his sister.', 'less smart'),
        ('This is the most fastest car.', 'fastest'),
        ('She is moreolder than me.', 'older'),
        ('He is moststronger than his opponent.', 'stronger'),
        ('This is more better than nothing.', 'better'),
        ('She is mostbeautiful in the world.', 'the most'),
        ('He is morehardworking than anyone.', 'hardworking'),
        ('This is the mostsimple solution.', 'simplest'),
        ('She is morecareful than before.', 'more careful'),
        ('He is mostpatient of all.', 'the most'),
        ('This is moreeasier than I thought.', 'easier'),
        ('She is mostskilled player.', 'the most'),
        ('He is moregenerous than he seems.', 'more generous'),
        ('This is mostdifficult question.', 'the most'),
        ('She is morecreative than her peers.', 'more creative'),
        ('He is mostpopular student.', 'the most'),
        ('This is morecomplicated than necessary.', 'more complicated'),
        ('She is mostaccomplished artist.', 'the most'),
        ('He is morededicated than his colleagues.', 'more dedicated'),
        ('This is mostchallenging project.', 'the most'),
        ('She is moresuccessful than expected.', 'more successful'),
        ('He is mosttalented musician.', 'the most'),
        ('This is moreadvanced technology.', 'more advanced'),
        ('She is mostknowledgeable person.', 'the most'),
        ('He is moreexperienced than I am.', 'more experienced'),
        ('This is mostinteresting book.', 'the most'),
        ('She is morepassionate about her work.', 'more passionate'),
        ('He is mostreliable team member.', 'the most'),
        ('This is morepractical approach.', 'more practical'),
        ('She is mostinfluential leader.', 'the most'),
    ],
    "PARALLELISM": [
        ('She likes to swim, running, and biking.', 'to swim, to run, and to bike'),
        ('He enjoys reading, to write, and drawing.', 'reading, writing, and drawing'),
        ('They want to learn, studying, and practice.', 'to learn, to study, and to practice'),
        ('We plan hiking, to swim, and fishing.', 'to hike, to swim, and to fish'),
        ('She prefers to walk, jogging, and cycling.', 'to walk, to jog, and to cycle'),
        ('He likes cooking, to clean, and shopping.', 'cooking, cleaning, and shopping'),
        ('They enjoy to hike, camping, and fish.', 'hiking, camping, and fishing'),
        ('We started to pack, cooking, and leaving.', 'packing, cooking, and leaving'),
        ('She needs to study, working, and resting.', 'studying, working, and resting'),
        ('He wants playing guitar, to sing, and dance.', 'to play guitar, to sing, and to dance'),
        ('They plan to travel, exploring, and relaxing.', 'traveling, exploring, and relaxing'),
        ('We enjoy reading books, to watch movies, and play games.', 'reading books, watching movies, and playing games'),
        ('She decided to exercise, eat healthy, and sleep well.', 'to exercise, to eat healthy, and to sleep well'),
        ('He likes swimming, to jog, and cycling.', 'swimming, jogging, and cycling'),
        ('They prefer to cook, baking, and grilling.', 'cooking, baking, and grilling'),
        ('We started learning Spanish, to speak French, and study German.', 'learning Spanish, speaking French, and studying German'),
        ('She enjoys to paint, drawing, and sculpting.', 'painting, drawing, and sculpting'),
        ('He prefers to read, listening, and discussing.', 'reading, listening, and discussing'),
        ('They like cooking, to bake, and fry.', 'cooking, baking, and frying'),
        ('We decided to run, cycling, and to swim.', 'running, cycling, and swimming'),
        ('She started writing, to edit, and publishing.', 'writing, editing, and publishing'),
        ('He enjoys hiking, to camp, and fish.', 'hiking, camping, and fishing'),
        ('They prefer reading, to write, and discuss.', 'reading, writing, and discussing'),
        ('We want to learn French, studying Spanish, and Italian.', 'learning French, studying Spanish, and studying Italian'),
        ('She likes to dance, singing, and acting.', 'dancing, singing, and acting'),
        ('He prefers cooking, to bake, and to grill.', 'cooking, baking, and grilling'),
        ('They enjoy to hike, camping, and to fish.', 'hiking, camping, and fishing'),
        ('We started to read, writing, and edit.', 'reading, writing, and editing'),
        ('She likes shopping, to cook, and bake.', 'shopping, cooking, and baking'),
        ('He enjoys playing tennis, to swim, and jog.', 'playing tennis, swimming, and jogging'),
        ('They prefer to drive, flying, and sailing.', 'driving, flying, and sailing'),
        ('We plan to move, packing, and clean.', 'moving, packing, and cleaning'),
        ('She started to jog, swim, and cycle.', 'jogging, swimming, and cycling'),
        ('He likes running, to cycle, and hike.', 'running, cycling, and hiking'),
        ('They want learning French, to study German.', 'to learn French, to study German'),
        ('We enjoy hiking, camping, and to fish.', 'hiking, camping, and fishing'),
        ('She prefers reading, writing, and to edit.', 'reading, writing, and editing'),
        ('He started to cook, baking, and grill.', 'cooking, baking, and grilling'),
        ('They like to read, write, and draw.', 'to read, to write, and to draw'),
        ('We plan hiking, to swim, and to cycle.', 'to hike, to swim, and to cycle'),
    ],
    "RUN_ON_SENTENCE": [
        ('I love to read she prefers movies.', 'I love to read; she prefers movies.'),
        ('The cat is black the dog is white.', 'The cat is black, and the dog is white.'),
        ('He went to the store he bought milk.', 'He went to the store, and he bought milk.'),
        ('She studied hard she passed.', 'She studied hard, so she passed.'),
        ('It was raining we stayed inside.', 'It was raining, so we stayed inside.'),
        ('The movie was long it was good.', 'The movie was long, but it was good.'),
        ('I wanted to go I was tired.', 'I wanted to go, but I was tired.'),
        ('She likes coffee he prefers tea.', 'She likes coffee, and he prefers tea.'),
        ('He finished the work he went home.', 'He finished the work, and he went home.'),
        ('She was tired she kept working.', 'She was tired, but she kept working.'),
        ('It was cold we wore jackets.', 'It was cold, so we wore jackets.'),
        ('The food was ready we ate.', 'The food was ready, and we ate.'),
        ('He called me I did not answer.', 'He called me, but I did not answer.'),
        ('They practiced daily they improved.', 'They practiced daily, so they improved.'),
        ('The project was hard we finished.', 'The project was hard, but we finished it.'),
        ('He is smart he is lazy.', 'He is smart, but he is lazy.'),
        ('She sang the audience clapped.', 'She sang, and the audience clapped.'),
        ('The sun set we went home.', 'The sun set, and we went home.'),
        ('I am tired I need sleep.', 'I am tired, and I need sleep.'),
        ('She left early she had a reason.', 'She left early, and she had a reason.'),
    ],
    "MISSING_COMMA": [
        ('After eating dinner we went for a walk.', 'After eating dinner, we went for a walk.'),
        ('Before the movie started we bought popcorn.', 'Before the movie started, we bought popcorn.'),
        ('When the bell rang the students left.', 'When the bell rang, the students left.'),
        ('Although it was raining we went outside.', 'Although it was raining, we went outside.'),
        ('Because she was tired she went to bed.', 'Because she was tired, she went to bed.'),
        ('Since he was late he missed the bus.', 'Since he was late, he missed the bus.'),
        ('If you study hard you will pass.', 'If you study hard, you will pass.'),
        ('When I was young I loved to play.', 'When I was young, I loved to play.'),
        ('After the meeting we discussed the plan.', 'After the meeting, we discussed the plan.'),
        ('Before you leave lock the door.', 'Before you leave, lock the door.'),
        ('While she was cooking the phone rang.', 'While she was cooking, the phone rang.'),
        ('Unless you hurry you will be late.', 'Unless you hurry, you will be late.'),
        ('Whenever I visit she makes cookies.', 'Whenever I visit, she makes cookies.'),
        ('Wherever you go I will follow.', 'Wherever you go, I will follow you.'),
        ('Since you asked I will tell you.', 'Since you asked, I will tell you.'),
        ('Although he tried he could not win.', 'Although he tried, he could not win.'),
        ('Because it was cold we stayed inside.', 'Because it was cold, we stayed inside.'),
        ('When she arrived the party started.', 'When she arrived, the party started.'),
        ('If it rains we will cancel.', 'If it rains, we will cancel.'),
        ('After breakfast he went to work.', 'After breakfast, he went to work.'),
        ('Despite being tired she finished.', 'Despite being tired, she finished.'),
        ('However hard he tried he failed.', 'However hard he tried, he failed.'),
        ('Until further notice the office is closed.', 'Until further notice, the office is closed.'),
        ('While the others slept she studied.', 'While the others slept, she studied.'),
        ('Before the sun rose they left.', 'Before the sun rose, they left.'),
        ('As soon as he arrived the meeting started.', 'As soon as he arrived, the meeting started.'),
        ('Provided that everything goes well we will win.', 'Provided that everything goes well, we will win.'),
        ('Even though she was busy she helped.', 'Even though she was busy, she helped.'),
        ('In order to succeed you must work hard.', 'In order to succeed, you must work hard.'),
        ('Once the decision is made there is no going back.', 'Once the decision is made, there is no going back.'),
    ],
    "TO_PAST_PARTICIPLE": [
        ('She wants to went home.', 'go'),
        ('He needs to ate more vegetables.', 'eat'),
        ('They plan to swam across the lake.', 'swim'),
        ('We hope to won the game.', 'win'),
        ('I want to wrote a letter.', 'write'),
        ('She decided to drove to work.', 'drive'),
        ('He hopes to flew to Paris.', 'fly'),
        ('They want to spoke to the manager.', 'speak'),
        ('We need to gave them the message.', 'give'),
        ('I plan to took a vacation.', 'take'),
        ('She needs to chose carefully.', 'choose'),
        ('He wants to broke the record.', 'break'),
        ('They hope to knew the answer.', 'know'),
        ('We want to saw the sunset.', 'see'),
        ('I decided to threw the ball.', 'throw'),
        ('She hopes to grew her business.', 'grow'),
        ('He plans to froze the food.', 'freeze'),
        ('They want to began the project.', 'begin'),
        ('We need to rang the bell.', 'ring'),
        ('I want to drank some water.', 'drink'),
        ('She decided to fell asleep.', 'fall'),
        ('He hopes to hid the treasure.', 'hide'),
        ('They need to shook hands.', 'shake'),
        ('We want to bit into the apple.', 'bite'),
        ('I plan to stole the show.', 'steal'),
        ('She wants to tore the paper.', 'tear'),
        ('He hopes to woke up early.', 'wake'),
        ('They want to swam in the ocean.', 'swim'),
        ('We need to blew out the candles.', 'blow'),
        ('I decided to drew a picture.', 'draw'),
        ('She hopes to grew taller.', 'grow'),
        ('He wants to froze the pipes.', 'freeze'),
        ('They need to sunk the ship.', 'sink'),
        ('We want to sprang into action.', 'spring'),
        ('I plan to ran a marathon.', 'run'),
        ('She hopes to wrote a book.', 'write'),
        ('He wants to sang a song.', 'sing'),
        ('They decide to left early.', 'leave'),
        ('We want to chose the best option.', 'choose'),
        ('I hope to felt better soon.', 'feel'),
    ],
    "EXPLAIN_DATIVE": [
        ('She explained me the problem.', 'explained the problem to me'),
        ('He told the news me.', 'told me the news'),
        ('They described me the situation.', 'described the situation to me'),
        ('We explained them the rules.', 'explained the rules to them'),
        ('She taught him English.', 'taught English to him'),
        ('He offered me the job.', 'offered the job to me'),
        ('They showed us the way.', 'showed the way to us'),
        ('She gave him the book.', 'gave the book to him'),
        ('He handed me the papers.', 'handed the papers to me'),
        ('They sent us the package.', 'sent the package to us'),
        ('She read me the letter.', 'read the letter to me'),
        ('He told us the story.', 'told the story to us'),
        ('They paid me the money.', 'paid the money to me'),
        ('She showed him the picture.', 'showed the picture to him'),
        ('He gave her the keys.', 'gave the keys to her'),
        ('They explained us the process.', 'explained the process to us'),
        ('She taught them the lesson.', 'taught the lesson to them'),
        ('He offered her the position.', 'offered the position to her'),
        ('They showed me the results.', 'showed the results to me'),
        ('She handed him the report.', 'handed the report to him'),
        ('He told her the truth.', 'told the truth to her'),
        ('They sent me the document.', 'sent the document to me'),
        ('She gave them the instructions.', 'gave the instructions to them'),
        ('He read her the poem.', 'read the poem to her'),
        ('They offered us the deal.', 'offered the deal to us'),
        ('She described him the plan.', 'described the plan to him'),
        ('He explained us why.', 'explained to us why'),
        ('They taught us the method.', 'taught the method to us'),
        ('She told him what happened.', 'told him about what happened'),
        ('He showed her how to do it.', 'showed her how to do it'),
    ],
    "MISSING_ARTICLE": [
        ('In future we will do better.', 'in the future'),
        ('For few weeks the shop was closed.', 'for a few weeks'),
        ('She is student.', 'a student'),
        ('He went to shop.', 'the shop'),
        ('They live in small town.', 'a small town'),
        ('We need help.', 'some help'),
        ('She has headache.', 'a headache'),
        ('He made mistake.', 'a mistake'),
        ('They won prize.', 'a prize'),
        ('We had good time.', 'a good time'),
        ('She is at door.', 'at the door'),
        ('He went to office.', 'to the office'),
        ('They are in garden.', 'in the garden'),
        ('She is best player.', 'the best player'),
        ('He is president.', 'the president'),
        ('They found solution.', 'a solution'),
        ('We need discuss it.', 'to discuss it'),
        ('She has good reason.', 'a good reason'),
        ('He is teacher.', 'a teacher'),
        ('They visited museum.', 'the museum'),
        ('We watched movie.', 'a movie'),
        ('She read book.', 'a book'),
        ('He plays piano.', 'the piano'),
        ('They went to concert.', 'a concert'),
        ('We live in apartment.', 'an apartment'),
        ('She needs umbrella.', 'an umbrella'),
        ('He drove truck.', 'a truck'),
        ('She wore dress.', 'a dress'),
        ('He bought suit.', 'a suit'),
        ('They took vacation.', 'a vacation'),
    ],
}


def main():
    p = UnifiedPipeline()
    cat_results = {}
    total_found = 0
    total_expected = 0
    t0 = time.time()
    for cat, tests in CATEGORIES.items():
        found = 0
        missed = []
        for sent, expected in tests:
            results = p.check(sent)
            rule_ids = [r["rule_id"] for r in results]
            # Check if any rule matches
            matched = False
            for r in results:
                if cat.upper() in r["rule_id"].upper() or r["rule_id"].upper() in cat.upper():
                    matched = True
                    break
                # Also check specific mappings
                if cat == "DIDNT_PAST_FORM" and r["rule_id"] == "DIDNT_PAST_FORM":
                    matched = True
                    break
                if cat == "WRONG_PAST_PARTICIPLE" and r["rule_id"] == "WRONG_PAST_PARTICIPLE":
                    matched = True
                    break
                if cat == "MODAL_WRONG_FORM" and r["rule_id"] == "MODAL_WRONG_FORM":
                    matched = True
                    break
                if cat == "RUN_ON_SENTENCE" and r["rule_id"] == "RUN_ON_SENTENCE":
                    matched = True
                    break
                if cat == "COMMA_SPLICE" and r["rule_id"] == "COMMA_SPLICE":
                    matched = True
                    break
                if cat == "DOUBLE_COMPARATIVE" and r["rule_id"] in ("DOUBLE_COMPARATIVE", "DOUBLE_SUPERLATIVE"):
                    matched = True
                    break
                if cat == "EXPLAIN_DATIVE" and r["rule_id"] == "EXPLAIN_DATIVE":
                    matched = True
                    break
                if cat == "TO_PAST_PARTICIPLE" and r["rule_id"] == "TO_PAST_PARTICIPLE":
                    matched = True
                    break
                if cat == "MISSING_ARTICLE" and r["rule_id"] in ("MISSING_ARTICLE", "MISSING_ARTICLE_PHRASES"):
                    matched = True
                    break
                if cat == "MISSING_APOSTROPHE" and r["rule_id"] in ("MISSING_APOSTROPHE", "POSSESSIVE_APOSTROPHE"):
                    matched = True
                    break
                if cat == "MISSING_COMMA" and r["rule_id"] == "MISSING_COMMA_INTRO":
                    matched = True
                    break
                if cat == "PREPOSITION_COLLOCATION" and r["rule_id"] == "PREPOSITION_COLLOCATION":
                    matched = True
                    break
                if cat == "PARALLELISM" and r["rule_id"] == "PARALLELISM":
                    matched = True
                    break
                if cat == "ARTICLE_MISSING" and r["rule_id"] in ("ARTICLE_MISSING", "ARTICLE_A_AN", "MISSING_ARTICLE"):
                    matched = True
                    break
                if cat == "DO_SUPPORT" and r["rule_id"] == "DO_SUPPORT":
                    matched = True
                    break
                if cat == "SVA" and r["rule_id"] in ("SVA", "EXISTENTIAL_THERE_SVA", "MASS_NOUN_SVA"):
                    matched = True
                    break
                if cat == "TENSE_CONSISTENCY" and r["rule_id"] == "TENSE_CONSISTENCY":
                    matched = True
                    break
            if matched:
                found += 1
            else:
                missed.append((sent, expected, rule_ids))
        cat_results[cat] = (len(tests), found, missed)
        total_found += found
        total_expected += len(tests)

    elapsed = time.time() - t0
    print(f"")
    print(f"=== CATEGORY DETECTION RESULTS ===")
    print(f"{'Category':<25} {'Found':>6} {'Total':>6} {'Rate':>7}")
    print("-" * 50)
    for cat, (total, found, _) in sorted(cat_results.items()):
        rate = found / total * 100 if total > 0 else 0
        print(f"{cat:<25} {found:>6} {total:>6} {rate:>6.1f}%")
    print("-" * 50)
    print(f"{'TOTAL':<25} {total_found:>6} {total_expected:>6} {total_found/total_expected*100:>6.1f}%")
    print(f"Time: {elapsed:.1f}s")

    # Print missed errors
    print(f"")
    print(f"=== MISSED ERRORS BY CATEGORY ===")
    for cat, (total, found, missed) in sorted(cat_results.items()):
        if missed:
            print(f"\n{cat} ({total - found} missed):")
            for sent, expected, rules in missed[:5]:
                print(f'  "{sent[:80]}..." -> expected: {expected[:30]}')
                print(f'    Detected: {rules}')
            if len(missed) > 5:
                print(f"  ... and {len(missed) - 5} more")

if __name__ == "__main__":
    main()
