import sys
sys.path.insert(0, r'C:\Users\hemal\OneDrive\Documents\grammar_checker')
from unified_pipeline import UnifiedPipeline
p = UnifiedPipeline()

text = """Last Monday, I was planning to go to office early because my manager have scheduled an important meeting with all the team members. I reached the bus stop at around eight o'clock, but there was too many peoples waiting for the bus. The bus finally arrived after twenty minutes, and when I entered inside, I realized that I had forgot my wallet at home. I tried calling my brother, but he didn't answered the phone because he was sleeping. By the time I reached the office, the meeting already started and everyone were waiting for me. My manager asked me why I was late, and I explained him what had happened. He was not very happy, but he said that I should be more careful in future.
Yesterday, my friend and me decided to visit a new restaurant which recently opened near our house. We have heard many good reviews about the food, so we was expecting it to be very good. When we arrived at the restaurant, there were a long queue outside because the place was already crowded. After waiting for almost forty minutes, we finally got a table. The waiter gave us the menu and asked what would we like to order. My friend ordered a chicken biryani while I decided to try the special noodles. The food were served after twenty minutes, but the noodles was too spicy for me. We asked the waiter if he can bring some water, but he didn't came back for several minutes. In the end, we paid the bill and left the restaurant feeling a little disappointed.
Our company has recently launched a new software product which is designed for helping small businesses manage their customer data. The development team have worked on it since almost one year, and they has spent many hours testing different features. Although the product looks very promising, there are still several problems which needs to be fixed before it can be released to the public. Some customers has reported that the application loads very slowly when they uploads large files. The developers are currently working on solving these issues, but they said that it may takes another few weeks. The marketing team have already prepared several articles and advertisements, so everybody are waiting for the final release. If the technical problems will be solved soon, the company expects that the product will becomes very popular among small businesses.
Last weekend, I visited my grandparents house because they was celebrating their wedding anniversary. My cousins were also there, and everyone were helping to prepare the food. My grandmother asked me to brings some vegetables from the market, but I didn't had enough money with me. So, my cousin gave me some money and told me that I can return it later. After buying the vegetables, I came back home and realized that I had buy the wrong type of tomatoes. My grandmother laughed and said that it was not a big problem, but she asked me to be more carefully next time. In the evening, we all sat together and talked about our childhood memories. It was one of the most happiest days I have experienced in a long time.
I recently started learning about SEO because I want to improve my skills and become a better digital marketer. At first, I thought SEO was very easy, but after studying it for few weeks, I realized that there are much more things to learn than I expected. There is many technical factors that can affect a websites ranking, including page speed, internal linking, structured data and backlinks. I also learned that creating good content are not enough because search engines looks at many other signals before deciding how a page should rank. Sometimes I spends several hours analyzing competitors websites, but I still don't understands why some pages performs better than others. My goal is to build a tool which can automatically identify these problems and gives useful recommendations to website owners."""

issues = p.check(text)
print(f"Found {len(issues)} issues\n")
for e in sorted(issues, key=lambda x: x['start']):
    # Find sentence context
    start = max(0, e['start'] - 30)
    end = min(len(text), e['end'] + 30)
    context = text[start:end].replace('\n', ' ')
    print(f"[{e['start']:4d}] \"{e['original']}\" -> \"{e['replacement']}\" [{e['rule_id']}] conf={e['confidence']:.2f}")
    print(f"       ...{context}...")
    print()
